%YAML 1.1
---
version: '3.7'
services:
  hyperglass:
    image: checktheroads/hyperglass:latest
    networks:
    - hyperglass
    # restart: unless-stopped
    # ports:
    # - 8001:8001
    # volumes:
    # - ./devices.yaml:/opt/hyperglass/devices.yaml
    # - ./hyperglass.yaml:/opt/hyperglass/hyperglass.yaml
    # - ./commands.yaml:/opt/hyperglass/commands.yaml
    depends_on:
    - redis
    healthcheck:
      test: test "$$(curl -o /dev/null -s --user-agent docker-healthcheck http://localhost:8001 --write-out %{http_code})" = "200"
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:latest
    networks:
    - hyperglass
    # restart: unless-stopped
    command: [redis-server, --appendonly, 'yes']
    volumes:
    - redis-data:/data

volumes:
  redis-data:

networks:
  hyperglass:
    name: hyperglass
