name: Frontend Testing
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hyperglass/ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.22.0'
      - run: npm install --global pnpm@10.11.0
      - run: pnpm install --frozen-lockfile
      - run: echo '{}' > hyperglass.json
      - run: pnpm run format:check
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm run test --maxWorkers=2 --minWorkers=1
